spring:
  servlet:
    multipart:
      max-file-size: 400MB
      max-request-size: 400MB
  config:
    activate:
      on-profile: dev
logging:
  level:
    at.javaprofi.ocr.frame.backend.service: debug
server:
  port: 8083
